<?php
/**
 * @file
 * This module creates a form element that allows users to select
 * repeat rules for a date, and reworks the result into an iCal
 * RRULE string that can be stored in the database.
 *
 * The module also parses iCal RRULEs to create an array of dates
 * that meet their criteria.
 *
 * Other modules can use this API to add self-validating form elements
 * to their dates, and identify dates that meet the RRULE criteria.
 */

/**
 * Implements hook_element_info().
 */
function date_repeat_element_info() {
  $type['date_repeat_rrule'] = array(
    '#input' => TRUE,
    '#process' => array('date_repeat_rrule_process'),
    '#element_validate' => array('date_repeat_rrule_validate'),
    '#theme_wrappers' => array('date_repeat_rrule'),
  );
  $type['date_repeat_form_element_radios'] = array(
    '#input' => TRUE,
    '#process' => array('date_repeat_form_element_radios_process'),
    '#theme_wrappers' => array('container__radios'),
    '#pre_render' => array('form_pre_render_conditional_form_element'),
  );
  return $type;
}

/**
 * Implements hook_theme().
 */
function date_repeat_theme() {
  $path = backdrop_get_path('module', 'date_repeat');
  module_load_include('inc', 'date_repeat_field', 'date_repeat.theme');

  $base = array(
    'file' => 'date_repeat.theme.inc',
    'path' => "$path",
  );
  $themes = array(
    'date_repeat_current_exceptions' => array('render element' => 'element'),
    'date_repeat_current_additions' => array('render element' => 'element'),
    'date_repeat_rrule' => array('render element' => 'element'),
    'date_repeat_form_element' => $base + array('render element' => 'element'),
  );
  return $themes;
}

/**
 * Implements hook_theme_registry_alter().
 */
function date_repeat_theme_registry_alter(&$theme_registry) {
  $theme_registry['date_display_combination'] = array(
    'file' => 'date_repeat.theme.inc',
    'path' => backdrop_get_path('module', 'date_repeat'),
    'theme path' => backdrop_get_path('module', 'date_repeat'),
    'function' => 'theme_date_repeat_display_combination',
    'includes' => array(
      backdrop_get_path('module', 'date_repeat') . '/' . 'date_repeat.theme.inc',
    ),
    'preprocess functions' => array(
      'template_preprocess_date_display_combination',
    ),
  );
}

/**
 * Helper function for FREQ options.
 *
 * @return array
 *   Array of FREQ options.
 */
function date_repeat_freq_options() {
  return array(
    'DAILY' => t('Daily', array(), array('context' => 'datetime_singular')),
    'WEEKLY' => t('Weekly', array(), array('context' => 'datetime_singular')),
    'MONTHLY' => t('Monthly', array(), array('context' => 'datetime_singular')),
    'YEARLY' => t('Yearly', array(), array('context' => 'datetime_singular')),
  );
}

/**
 * Helper function for interval options.
 *
 * @return array
 *   Array of 365 intervals.
 */
function date_repeat_interval_options() {
  $options = range(0, 366);
  unset($options[0]);

  return $options;
}

/**
 * Helper function for FREQ options.
 *
 * @param bool $translated
 *
 * @return array
 *   Translated and untranslated arrays of the iCal day of week names.
 *   We need the untranslated values for date_modify(), translated
 *   values when displayed to user.
 */
function date_repeat_dow_day_options($translated = TRUE) {
  return array(
    'SU' => $translated ? t('Sunday', array(), array('context' => 'day_name')) : 'Sunday',
    'MO' => $translated ? t('Monday', array(), array('context' => 'day_name')) : 'Monday',
    'TU' => $translated ? t('Tuesday', array(), array('context' => 'day_name')) : 'Tuesday',
    'WE' => $translated ? t('Wednesday', array(), array('context' => 'day_name')) : 'Wednesday',
    'TH' => $translated ? t('Thursday', array(), array('context' => 'day_name')) : 'Thursday',
    'FR' => $translated ? t('Friday', array(), array('context' => 'day_name')) : 'Friday',
    'SA' => $translated ? t('Saturday', array(), array('context' => 'day_name')) : 'Saturday',
  );
}

/**
 * Helper function for FREQ options.
 *
 * @param bool $translated
 * @param int $length
 *
 * @return array
 *   Translated and untranslated arrays of the iCal abbreviated day of week names.
 */
function date_repeat_dow_day_options_abbr($translated = TRUE, $length = 3) {
  $return = array();
  switch ($length) {
    case 1:
      $context = 'day_abbr1';
      break;

    case 2:
      $context = 'day_abbr2';
      break;

    default:
      $context = '';
      break;
  }
  foreach (date_repeat_dow_day_untranslated() as $key => $day) {
    $return[$key] = $translated ? t(substr($day, 0, $length), array(), array('context' => $context)) : substr($day, 0, $length);
  }
  return $return;
}

/**
 * Helper function for weekdays translated.
 *
 * @return array
 *   Array of translated weekdays.
 */
function date_repeat_dow_day_untranslated() {
  static $date_repeat_weekdays;
  if (empty($date_repeat_weekdays)) {
    $date_repeat_weekdays = array(
      'SU' => 'Sunday',
      'MO' => 'Monday',
      'TU' => 'Tuesday',
      'WE' => 'Wednesday',
      'TH' => 'Thursday',
      'FR' => 'Friday',
      'SA' => 'Saturday'
    );
  }
  return $date_repeat_weekdays;
}

/**
 * Helper function for weekdays order.
 *
 * @param array $weekdays
 *
 * @return array
 */
function date_repeat_dow_day_options_ordered($weekdays) {
  $day_keys = array_keys($weekdays);
  $day_values = array_values($weekdays);
  for ($i = 1; $i <= system_date_format_load('first_day'); $i++) {
    $last_key = array_shift($day_keys);
    array_push($day_keys, $last_key);
    $last_value = array_shift($day_values);
    array_push($day_values, $last_value);
  }
  $weekdays = array_combine($day_keys, $day_values);
  return $weekdays;
}

/**
 * Helper function for BYDAY options.
 *
 * @return array
 *   Array of BYDAY options.
 */
function date_repeat_dow_count_options() {
  return array('' => t('Every', array(), array('context' => 'date_order'))) + date_repeat_order_translated();
}

/**
 * Helper function for BYDAY options.
 *
 * @return array
 *   Array of options like -1SU and 2TU
 */
function date_repeat_dow_options() {
  $options = array();
  foreach (date_repeat_dow_count_options() as $count_key => $count_value) {
    foreach (date_repeat_dow_day_options() as $dow_key => $dow_value) {
      $options[$count_key . $dow_key] = $count_value . ' ' . $dow_value;
    }
  }
  return $options;
}

/**
 * Translate a day of week position to the iCal day name.
 *
 * Used with date_format($date, 'w') or get_variable('date_first_day'),
 * which return 0 for Sunday, 1 for Monday, etc.
 *
 * dow 2 becomes 'TU', dow 3 becomes 'WE', and so on.
 */
function date_repeat_dow2day($dow) {
  $days_of_week = array_keys(date_repeat_dow_day_options(FALSE));
  return $days_of_week[$dow];
}

/**
 * Shift the array of iCal day names into the right order for a specific week start day.
 */
function date_repeat_days_ordered($week_start_day) {
  $days = array_flip(array_keys(date_repeat_dow_day_options(FALSE)));
  $start_position = $days[$week_start_day];
  $keys = array_flip($days);
  if ($start_position > 0) {
    for ($i = 1; $i <= $start_position; $i++) {
      $last = array_shift($keys);
      array_push($keys, $last);
    }
  }
  return $keys;
}

/**
 * Build a description of an iCal rule.
 *
 * Constructs a human-readable description of the rule.
 *
 * @param string $rrule
 * @param string $format
 *
 * @return string|null
 */
function date_repeat_rrule_description($rrule, $format = 'D M d Y') {
  // Empty or invalid value.
  if (empty($rrule) || !strstr($rrule, 'RRULE')) {
    return;
  }

  module_load_include('inc', 'date_repeat', 'includes/date_repeat_ical');
  module_load_include('inc', 'date_repeat', 'includes/date_repeat_calc');

  $parts = date_repeat_split_rrule($rrule);
  $additions = $parts[2];
  $exceptions = $parts[1];
  $rrule = $parts[0];
  if ($rrule['FREQ'] == 'NONE') {
    return;
  }

  // Make sure there will be an empty description for any unused parts.
  $description = array(
    '!interval' => '',
    '!byday' => '',
    '!bymonth' => '',
    '!count' => '',
    '!until' => '',
    '!except' => '',
    '!additional' => '',
    '!week_starts_on' => '',
  );
  $interval = date_repeat_interval_options();
  switch ($rrule['FREQ']) {
    case 'WEEKLY':
      $description['!interval'] = format_plural($rrule['INTERVAL'], 'every week', 'every @count weeks') . ' ';
      break;

    case 'MONTHLY':
      $description['!interval'] = format_plural($rrule['INTERVAL'], 'every month', 'every @count months') . ' ';
      break;

    case 'YEARLY':
      $description['!interval'] = format_plural($rrule['INTERVAL'], 'every year', 'every @count years') . ' ';
      break;

    default:
      $description['!interval'] = format_plural($rrule['INTERVAL'], 'every day', 'every @count days') . ' ';
      break;
  }

  if (!empty($rrule['BYDAY'])) {
    $days = date_repeat_dow_day_options();
    $counts = date_repeat_dow_count_options();
    $results = array();
    foreach ($rrule['BYDAY'] as $byday) {
      // Get the numeric part of the BYDAY option, i.e. +3 from +3MO.
      $day = substr($byday, -2);
      $count = str_replace($day, '', $byday);
      if (!empty($count)) {
        // See if there is a 'pretty' option for this count, i.e. +1 => First.
        $order = array_key_exists($count, $counts) ? strtolower($counts[$count]) : $count;
        $results[] = trim(t('!repeats_every_interval on the !date_order !day_of_week',
        array(
          '!repeats_every_interval ' => '',
          '!date_order' => $order,
          '!day_of_week' => $days[$day]
        )));
      }
      else {
        $results[] = trim(t('!repeats_every_interval every !day_of_week',
        array('!repeats_every_interval ' => '', '!day_of_week' => $days[$day])));
      }
    }
    $description['!byday'] = implode(' ' . t('and') . ' ', $results);
  }
  if (!empty($rrule['BYMONTH'])) {
    if (count($rrule['BYMONTH']) < 12) {
      $results = array();
      $months = date_month_names();
      foreach ($rrule['BYMONTH'] as $month) {
        $results[] = $months[$month];
      }
      if (!empty($rrule['BYMONTHDAY'])) {
        $description['!bymonth'] = trim(t('!repeats_every_interval on the !month_days of !month_names',
        array(
          '!repeats_every_interval ' => '',
          '!month_days' => implode(', ', $rrule['BYMONTHDAY']),
          '!month_names' => implode(', ', $results)
        )));
      }
      else {
        $description['!bymonth'] = trim(t('!repeats_every_interval on !month_names',
        array(
          '!repeats_every_interval ' => '',
          '!month_names' => implode(', ', $results)
        )));
      }
    }
  }
  if ($rrule['INTERVAL'] < 1) {
    $rrule['INTERVAL'] = 1;
  }
  if (!empty($rrule['COUNT'])) {
    $description['!count'] = trim(t('!repeats_every_interval !count times',
    array('!repeats_every_interval ' => '', '!count' => $rrule['COUNT'])));
  }
  if (!empty($rrule['UNTIL'])) {
    $until = date_repeat_ical_date($rrule['UNTIL'], 'UTC');
    date_timezone_set($until, date_default_timezone_object());
    $description['!until'] = trim(t('!repeats_every_interval until !until_date',
    array(
      '!repeats_every_interval ' => '',
      '!until_date' => date_format_date($until, 'custom', $format)
    )));
  }
  if ($exceptions) {
    $values = array();
    foreach ($exceptions as $exception) {
      $except = date_repeat_ical_date($exception, 'UTC');
      date_timezone_set($except, date_default_timezone_object());
      $values[] = date_format_date($except, 'custom', $format);
    }
    $description['!except'] = trim(t('!repeats_every_interval except !except_dates',
    array(
      '!repeats_every_interval ' => '',
      '!except_dates' => implode(', ', $values)
    )));
  }
  if (!empty($rrule['WKST'])) {
    $day_names = date_repeat_dow_day_options();
    $description['!week_starts_on'] = trim(t('!repeats_every_interval where the week start on !day_of_week',
    array('!repeats_every_interval ' => '', '!day_of_week' => $day_names[trim($rrule['WKST'])])));
  }
  if ($additions) {
    $values = array();
    foreach ($additions as $addition) {
      $add = date_repeat_ical_date($addition, 'UTC');
      date_timezone_set($add, date_default_timezone_object());
      $values[] = date_format_date($add, 'custom', $format);
    }
    $description['!additional'] = trim(t('Also includes !additional_dates.',
    array('!additional_dates' => implode(', ', $values))));
  }
  $output = t('Repeats !interval !bymonth !byday !count !until !except. !additional', $description);
  // Removes double whitespaces from Repeat tile.
  $output = preg_replace('/\s+/', ' ', $output);
  // Removes whitespace before full stop ".", at the end of the title.
  $output = str_replace(' .', '.', $output);
  return $output;
}

/**
 * Parse an iCal rule into a parsed RRULE array and an EXDATE array.
 *
 * @param string $rrule
 *
 * @return array
 *   An array containing arrays of rrule, exceptions and additions.
 */
function date_repeat_split_rrule($rrule) {
  $parts = explode("\n", str_replace("\r\n", "\n", $rrule));
  $rrule = array();
  $exceptions = array();
  $additions = array();
  $additions = array();
  foreach ($parts as $part) {
    if (strstr($part, 'RRULE')) {
      $cleanded_part = str_replace('RRULE:', '', $part);
      $rrule = (array) date_repeat_ical_parse_rrule('RRULE:', $cleanded_part);
    }
    elseif (strstr($part, 'EXDATE')) {
      $exdate = str_replace('EXDATE:', '', $part);
      $exceptions = (array) date_repeat_ical_parse_exceptions('EXDATE:', $exdate);
      unset($exceptions['DATA']);
    }
    elseif (strstr($part, 'RDATE')) {
      $rdate = str_replace('RDATE:', '', $part);
      $additions = (array) date_repeat_ical_parse_exceptions('RDATE:', $rdate);
      unset($additions['DATA']);
    }
  }
  return array($rrule, $exceptions, $additions);
}

/**
 * Analyze a RRULE and return dates that match it.
 *
 * @param string $rrule
 * @param string|array $start
 * @param string|array $end
 * @param array $exceptions
 * @param string|null $timezone
 * @param array $additions
 *
 * @return array
 *   Array of days.
 */
function date_repeat_calc($rrule, $start, $end, $exceptions = array(), $timezone = NULL, $additions = array()) {
  module_load_include('inc', 'date_repeat', 'includes/date_repeat_calc');
  return _date_repeat_calc($rrule, $start, $end, $exceptions, $timezone, $additions);
}

/**
 * Generate the repeat rule setting form.
 */
function date_repeat_rrule_process($element, &$form_state, $form) {
  module_load_include('inc', 'date_repeat', 'includes/date_repeat_form');
  return _date_repeat_rrule_process($element, $form_state, $form);
}

/**
 * Process function for 'date_repeat_form_element_radios'.
 */
function date_repeat_form_element_radios_process($element) {
  $childrenkeys = element_children($element);

  if (count($element['#options']) &&
      count($element['#options']) == count($childrenkeys)) {
    $weight = 0;
    $children = array();
    $classes = isset($element['#div_classes']) ?
      $element['#div_classes'] : array();
    foreach ($childrenkeys as $childkey) {
      $children[$childkey] = $element[$childkey];
      unset($element[$childkey]);
    }
    foreach ($element['#options'] as $key => $choice) {
      $currentchildkey = array_shift($childrenkeys);
      $weight += 0.001;
      $class = array_shift($classes);
      $element += array($key => array());
      $parents_for_id = array_merge($element['#parents'], array($key));
      $element[$key] += array(
        '#prefix' => '<div' . ($class ? " class=\"{$class}\"" : '') . '>',
        '#type' => 'radio',
        '#title' => $choice,
        '#title_display' => 'invisible',
        '#return_value' => $key,
        '#default_value' => isset($element['#default_value']) ?
        $element['#default_value'] : NULL,
        '#attributes' => $element['#attributes'],
        '#parents' => $element['#parents'],
        '#id' => backdrop_html_id('edit-' . implode('-', $parents_for_id)),
        '#ajax' => isset($element['#ajax']) ? $element['ajax'] : NULL,
        '#weight' => $weight,
        '#theme_wrappers' => array(),
        '#suffix' => ' ',
      );

      $child = $children[$currentchildkey];

      $weight += 0.001;

      $child['#weight'] = $weight;
      $child['#title_display'] = 'invisible';
      $child['#suffix'] = (!empty($child['#suffix']) ? $child['#suffix'] : '') .
        '</div>';
      $child['#parents'] = $element['#parents'];
      array_pop($child['#parents']);
      array_push($child['#parents'], $currentchildkey);

      $element_prototype = element_info($child['#type']);
      $old_wrappers = array();
      if (isset($child['#theme_wrappers'])) {
        $old_wrappers += $child['#theme_wrappers'];
      }
      if (isset($element_prototype['#theme_wrappers'])) {
        $old_wrappers += $element_prototype['#theme_wrappers'];
      }

      $child['#theme_wrappers'] = array();

      foreach ($old_wrappers as $wrapper) {
        if ($wrapper != 'form_element') {
          $child['#theme_wrappers'][] = $wrapper;
        }
      }

      $element[$currentchildkey] = $child;
    }
  }

  return $element;
}

/**
 ****************************************************************************
 * Helper functions below replicated from the date_api module since they were
 * not included in the date module when added to Backdrop core.
 ****************************************************************************
 */

/**
 * For converting back and forth from '+1' to 'First'.
 * Originally date_order_translated().
 *
 * @return array
 */
function date_repeat_order_translated() {
    return array(
        '+1' => t('First', array(), array('context' => 'date_order')),
        '+2' => t('Second', array(), array('context' => 'date_order')),
        '+3' => t('Third', array(), array('context' => 'date_order')),
        '+4' => t('Fourth', array(), array('context' => 'date_order')),
        '+5' => t('Fifth', array(), array('context' => 'date_order')),
        '-1' => t('Last', array(), array('context' => 'date_order_reverse')),
        '-2' => t('Next to last', array(), array('context' => 'date_order_reverse')),
        '-3' => t('Third from last', array(), array('context' => 'date_order_reverse')),
        '-4' => t('Fourth from last', array(), array('context' => 'date_order_reverse')),
        '-5' => t('Fifth from last', array(), array('context' => 'date_order_reverse')),
    );
}

/**
 * Creates an array of ordered strings, using English text when possible.
 * Originally date_order().
 *
 * @return array
 */
function date_repeat_order() {
    return array(
        '+1' => 'First',
        '+2' => 'Second',
        '+3' => 'Third',
        '+4' => 'Fourth',
        '+5' => 'Fifth',
        '-1' => 'Last',
        '-2' => '-2',
        '-3' => '-3',
        '-4' => '-4',
        '-5' => '-5',
    );
}

/**
 * Function to figure out the bundle name for an entity.
 * Originally date_get_entity_bundle().
 *
 * @param string $entity_type
 * @param object|string $entity
 *
 * @return string
 */
function date_repeat_get_entity_bundle($entity_type, $entity) {
  switch ($entity_type) {
    case 'field_collection_item':
      $bundle = $entity->field_name;
      break;

    default:
      $bundle = field_extract_bundle($entity_type, $entity);
      break;
  }
  // If there is no bundle name, field_info() uses the entity name as the bundle
  // name in its arrays.
  if (empty($bundle)) {
    $bundle = $entity_type;
  }
  return $bundle;
}

/**
 * Create replacement values for deprecated timezone names.
 * Originally _date_timezone_replacement().
 *
 * @param string $old
 *
 * @return string
 */
function _date_repeat_timezone_replacement($old) {
  $replace = array(
    'Brazil/Acre' => 'America/Rio_Branco',
    'Brazil/DeNoronha' => 'America/Noronha',
    'Brazil/East' => 'America/Recife',
    'Brazil/West' => 'America/Manaus',
    'Canada/Atlantic' => 'America/Halifax',
    'Canada/Central' => 'America/Winnipeg',
    'Canada/East-Saskatchewan' => 'America/Regina',
    'Canada/Eastern' => 'America/Toronto',
    'Canada/Mountain' => 'America/Edmonton',
    'Canada/Newfoundland' => 'America/St_Johns',
    'Canada/Pacific' => 'America/Vancouver',
    'Canada/Saskatchewan' => 'America/Regina',
    'Canada/Yukon' => 'America/Whitehorse',
    'CET' => 'Europe/Berlin',
    'Chile/Continental' => 'America/Santiago',
    'Chile/EasterIsland' => 'Pacific/Easter',
    'CST6CDT' => 'America/Chicago',
    'Cuba' => 'America/Havana',
    'EET' => 'Europe/Bucharest',
    'Egypt' => 'Africa/Cairo',
    'Eire' => 'Europe/Belfast',
    'EST' => 'America/New_York',
    'EST5EDT' => 'America/New_York',
    'GB' => 'Europe/London',
    'GB-Eire' => 'Europe/Belfast',
    'Etc/GMT' => 'UTC',
    'Etc/GMT+0' => 'UTC',
    'Etc/GMT+1' => 'UTC',
    'Etc/GMT+10' => 'UTC',
    'Etc/GMT+11' => 'UTC',
    'Etc/GMT+12' => 'UTC',
    'Etc/GMT+2' => 'UTC',
    'Etc/GMT+3' => 'UTC',
    'Etc/GMT+4' => 'UTC',
    'Etc/GMT+5' => 'UTC',
    'Etc/GMT+6' => 'UTC',
    'Etc/GMT+7' => 'UTC',
    'Etc/GMT+8' => 'UTC',
    'Etc/GMT+9' => 'UTC',
    'Etc/GMT-0' => 'UTC',
    'Etc/GMT-1' => 'UTC',
    'Etc/GMT-10' => 'UTC',
    'Etc/GMT-11' => 'UTC',
    'Etc/GMT-12' => 'UTC',
    'Etc/GMT-13' => 'UTC',
    'Etc/GMT-14' => 'UTC',
    'Etc/GMT-2' => 'UTC',
    'Etc/GMT-3' => 'UTC',
    'Etc/GMT-4' => 'UTC',
    'Etc/GMT-5' => 'UTC',
    'Etc/GMT-6' => 'UTC',
    'Etc/GMT-7' => 'UTC',
    'Etc/GMT-8' => 'UTC',
    'Etc/GMT-9' => 'UTC',
    'Etc/GMT0' => 'UTC',
    'Etc/Greenwich' => 'UTC',
    'Etc/UCT' => 'UTC',
    'Etc/Universal' => 'UTC',
    'Etc/UTC' => 'UTC',
    'Etc/Zulu' => 'UTC',
    'Factory' => 'UTC',
    'GMT' => 'UTC',
    'GMT+0' => 'UTC',
    'GMT-0' => 'UTC',
    'GMT0' => 'UTC',
    'Hongkong' => 'Asia/Hong_Kong',
    'HST' => 'Pacific/Honolulu',
    'Iceland' => 'Atlantic/Reykjavik',
    'Iran' => 'Asia/Tehran',
    'Israel' => 'Asia/Tel_Aviv',
    'Jamaica' => 'America/Jamaica',
    'Japan' => 'Asia/Tokyo',
    'Kwajalein' => 'Pacific/Kwajalein',
    'Libya' => 'Africa/Tunis',
    'MET' => 'Europe/Budapest',
    'Mexico/BajaNorte' => 'America/Tijuana',
    'Mexico/BajaSur' => 'America/Mazatlan',
    'Mexico/General' => 'America/Mexico_City',
    'MST' => 'America/Boise',
    'MST7MDT' => 'America/Boise',
    'Navajo' => 'America/Phoenix',
    'NZ' => 'Pacific/Auckland',
    'NZ-CHAT' => 'Pacific/Chatham',
    'Poland' => 'Europe/Warsaw',
    'Portugal' => 'Europe/Lisbon',
    'PRC' => 'Asia/Chongqing',
    'PST8PDT' => 'America/Los_Angeles',
    'ROC' => 'Asia/Taipei',
    'ROK' => 'Asia/Seoul',
    'Singapore' => 'Asia/Singapore',
    'Turkey' => 'Europe/Istanbul',
    'US/Alaska' => 'America/Anchorage',
    'US/Aleutian' => 'America/Adak',
    'US/Arizona' => 'America/Phoenix',
    'US/Central' => 'America/Chicago',
    'US/East-Indiana' => 'America/Indianapolis',
    'US/Eastern' => 'America/New_York',
    'US/Hawaii' => 'Pacific/Honolulu',
    'US/Indiana-Starke' => 'America/Indiana/Knox',
    'US/Michigan' => 'America/Detroit',
    'US/Mountain' => 'America/Boise',
    'US/Pacific' => 'America/Los_Angeles',
    'US/Pacific-New' => 'America/Los_Angeles',
    'US/Samoa' => 'Pacific/Samoa',
    'W-SU' => 'Europe/Moscow',
    'WET' => 'Europe/Paris',
  );
  if (array_key_exists($old, $replace)) {
    return $replace[$old];
  }
  else {
    return $old;
  }
}
